services:
  vault-agent:
    image: hashicorp/vault:latest
    container_name: dofRessTrack-vault-agent
    command: vault agent -config=/vault/config/agent.hcl
    cap_add:
      - IPC_LOCK
    volumes:
      - ./agent-config:/vault/config:ro,z
      - shared_secrets:/shared/secrets:z
    environment:
      VAULT_ADDR: "https://vault.appez.cafe"
    restart: unless-stopped
    networks:
      - external-outbound

  dofRessTrack:
    image: registry.appez.cafe/dofresstrack:latest
    container_name: dofRessTrack
    volumes:
      - shared_secrets:/secrets:ro
      - static_files:/app/staticfiles:ro
      - media_files:/app/media:rw
    depends_on:
      - vault-agent
    networks:
      - internal-network
      - external-outbound
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: dofRessTrack-nginx
    volumes:
      - static_files:/usr/share/nginx/html/static:ro,z
      - media_files:/usr/share/nginx/html/media:ro,z
    depends_on:
      - dofRessTrack
    networks:
      - nginx-network
      - internal-network
    restart: unless-stopped

volumes:
  shared_secrets:
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=10m,uid=100
  static_files:
  media_files:

networks:
  nginx-network:
    name: nginx-network
    external: true
  internal-network:
    name: dofresstrack-internal-network
    internal: true
  external-outbound:
    name: dofresstrack-external-outbound
