# Generated by Django 6.0 on 2026-01-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='resources/images/')),
                ('resource_type', models.IntegerField(choices=[(0, 'ITEM'), (1, 'CRAFT'), (2, 'HARVEST'), (3, 'BOSS'), (4, 'MONSTER'), (5, 'WANTED'), (6, 'QUEST')])),
            ],
        ),
    ]
