# Generated by Django 6.0 on 2026-01-03 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_buyin_sellout'),
    ]

    operations = [
        migrations.CreateModel(
            name='RessourceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='resources/images/')),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='use_in',
            field=models.ManyToManyField(blank=True, related_name='used_for', to='tracker.resource'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.IntegerField(choices=[(0, 'ITEM'), (1, 'CRAFT'), (2, 'HARVEST'), (3, 'BOSS'), (4, 'MONSTER'), (5, 'WANTED'), (6, 'CARD'), (7, 'QUEST')]),
        ),
        migrations.AlterField(
            model_name='resource',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.ressourceimage'),
        ),
    ]
