# Generated by Django 6.0 on 2026-01-03 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_ressourceimage_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resource',
            new_name='Ressource',
        ),
    ]
