# Generated by Django 6.0 on 2026-01-03 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_rename_resource_ressource'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ressource',
            new_name='Resource',
        ),
        migrations.RenameModel(
            old_name='RessourceImage',
            new_name='ResourceImage',
        ),
        migrations.RenameModel(
            old_name='RessourceValue',
            new_name='ResourceValue',
        ),
    ]
