# Generated by Django 6.0 on 2026-01-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_rename_ressource_resource_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyin',
            name='price',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='buyin',
            name='quantity',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='resourcevalue',
            name='value',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='sellout',
            name='price',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='sellout',
            name='quantity',
            field=models.SmallIntegerField(),
        ),
    ]
