# Generated by Django 6.0 on 2026-01-25 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_alter_buyin_price_alter_buyin_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcevalue',
            old_name='value',
            new_name='price',
        ),
    ]
