# Generated by Django 6.0 on 2026-02-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_rename_value_resourcevalue_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcevalue',
            name='price',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
