# Generated by Django 6.0 on 2026-03-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_alter_resourcevalue_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.IntegerField(choices=[(0, 'ITEM'), (1, 'CRAFT'), (2, 'HARVEST'), (3, 'BOSS'), (4, 'MONSTER'), (5, 'WANTED'), (6, 'CARD'), (7, 'QUEST'), (8, 'MISC')]),
        ),
    ]
