# Generated by Django 6.0 on 2026-03-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_alter_resource_resource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyin',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='resourcevalue',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellout',
            name='price',
            field=models.IntegerField(),
        ),
    ]
