# Generated by Django 6.0.3 on 2026-03-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_alter_buyin_price_alter_resourcevalue_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.IntegerField(choices=[(0, 'ITEM'), (1, 'CRAFT'), (2, 'HARVEST'), (3, 'BOSS'), (4, 'MONSTER'), (5, 'WANTED'), (6, 'CARD'), (7, 'QUEST'), (8, 'MISC'), (9, 'FAMILIAR')]),
        ),
    ]
